behaviors:
  CRTraining:
    trainer_type: sac
    max_steps: 50000000
    summary_freq: 5000
    time_horizon: 512
    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 32
      buffer_size: 102400
      learning_rate: 0.001
      learning_rate_schedule: constant
      buffer_init_steps: 128
      init_entcoef: 0.05
      save_replay_buffer: true
      tau: 0.005 #default
      steps_per_update: 30 #default
        
    network_settings:
        hidden_units: 44
        num_layers: 2
      
    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1
        gamma: 0.99

      # curiosity module
      curiosity:
        strength: 0.0003
        gamma: 0.9
        encoding_size: 64
        learning_rate: 0.001
        
environment_parameters:
  CRTraining:
    curriculum:
    - name: Lesson1_FixedRectSpawn # The '-' is important as this is a list
      completion_criteria:
        measure: reward
        behavior: CRTraining
        signal_smoothing: true
        min_lesson_length: 300
        require_reset: false
        threshold: 0.9
      value: 0.0
    - name: Lesson2 # The '-' is important as this is a list
      completion_criteria:
        measure: reward
        behavior: CRTraining
        signal_smoothing: true
        min_lesson_length: 300
        require_reset: false
        threshold: 0.9
      value: 1.0
    - name: Lesson3 # The '-' is important as this is a list
      completion_criteria:
        measure: reward
        behavior: CRTraining
        signal_smoothing: true
        min_lesson_length: 300
        require_reset: false
        threshold: 0.9
      value: 2.0  
    - name: Lesson4 # The '-' is important as this is a list
      completion_criteria:
        measure: reward
        behavior: CRTraining
        signal_smoothing: true
        min_lesson_length: 300
        require_reset: false
        threshold: 0.9
      value: 3.0 
    - name: Lesson5 # The '-' is important as this is a list
      completion_criteria:
        measure: reward
        behavior: CRTraining
        signal_smoothing: true
        min_lesson_length: 300
        require_reset: false
        threshold: 0.9
      value: 4.0  