behaviors:
  CRTraining:
    trainer_type: ppo
    max_steps: 12000000
    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 64
      buffer_size: 20480
      learning_rate: 3.0e-4
      learning_rate_schedule: constant
      num_epoch: 3
      lambd: 0.95
    
    network_settings:
        hidden_units: 32
      
    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1.0
        gamma: 0.99

      # curiosity module
      curiosity:
        strength: 0.005
        gamma: 0.99
        encoding_size: 64
        learning_rate: 3.0e-4
        
environment_parameters:
  tankPos:
    curriculum:
      - name: Lesson1 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: BoxCollecting
          signal_smoothing: true
          min_lesson_length: 100
          require_reset: false
          threshold: 0.5
        value: 5.0
      