behaviors:
  CRTraining:
    trainer_type: ppo
    max_steps: 50000000
    summary_freq: 16384
    time_horizon: 1024
    hyperparameters:
      # Hyperparameters common to PPO and SAC
      batch_size: 32
      buffer_size: 16384
      learning_rate: 0.00001
      learning_rate_schedule: linear
      num_epoch: 10
      lambd: 0.975
      beta: 0.00075
      beta_schedule: linear
      epsilon: 0.25
      epsilon_schedule: linear
        
    network_settings:
        hidden_units: 512
        num_layers: 4
        vis_encode_type: nature_cnn
      
    reward_signals:
      # environment reward (default)
      extrinsic:
        strength: 1
        gamma: 0.5

      # curiosity module
      curiosity:
        strength: 0.075
        gamma: 0.1
        encoding_size: 32
        learning_rate: 0.0001
        
environment_parameters:
  CRTraining:
    curriculum:
      - name: Lesson1_FixedRectSpawn # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: CRTraining
          signal_smoothing: true
          min_lesson_length: 100
          require_reset: false
          threshold: 0.9
        value: 0.0
      - name: Lesson2 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: CRTraining
          signal_smoothing: true
          min_lesson_length: 100
          require_reset: false
          threshold: 0.9
        value: 1.0
      - name: Lesson3 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: CRTraining
          signal_smoothing: true
          min_lesson_length: 100
          require_reset: false
          threshold: 0.85
        value: 2.0  
      - name: Lesson4 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: CRTraining
          signal_smoothing: true
          min_lesson_length: 100
          require_reset: false
          threshold: 0.85
        value: 3.0 
      - name: Lesson5 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: CRTraining
          signal_smoothing: true
          min_lesson_length: 100
          require_reset: false
          threshold: 0.8
        value: 4.0  
      - name: Lesson6_RandomRectSpawn # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: CRTraining
          signal_smoothing: true
          min_lesson_length: 100
          require_reset: false
          threshold: 0.9
        value: 5.0
      - name: Lesson6 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: CRTraining
          signal_smoothing: true
          min_lesson_length: 100
          require_reset: false
          threshold: 0.85
        value: 5.0  
      - name: Lesson7 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: CRTraining
          signal_smoothing: true
          min_lesson_length: 100
          require_reset: false
          threshold: 0.85
        value: 5.0 
      - name: Lesson8 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: CRTraining
          signal_smoothing: true
          min_lesson_length: 100
          require_reset: false
          threshold: 0.8
        value: 5.0 
      - name: Lesson9 # The '-' is important as this is a list
        completion_criteria:
          measure: reward
          behavior: CRTraining
          signal_smoothing: true
          min_lesson_length: 100
          require_reset: false
          threshold: 0.8
        value: 5.0 
